### create category
POST http://localhost:8080/category
Content-Type: application/json

{

  "categoryName": "electronics"
}
### create sub category
POST http://localhost:8080/category
Content-Type: application/json

{
  "parentId": 1,
  "categoryName": "build_tools"
}


### find all
GET http://localhost:8080/category

### find by id
GET http://localhost:8080/category/3

### delete by id
DELETE http://localhost:8080/category/4