
### create price
POST http://localhost:8080/prices
Content-Type: application/json

{
  "amount": 20.00,
  "description": "price from 05.11.2021",
  "currency": "",
  "productId": 1
}

### find all
GET http://localhost:8080/prices

### find by id
GET http://localhost:8080/prices/2

### delete by id
DELETE http://localhost:8080/prices/1

### update
PUT http://localhost:8080/prices
Content-Type: application/json

{
  "id": 1,
  "amount": 30,
  "description": "price from 05.11.2021",
  "currency": "USD"
}

### all by currency
GET http://localhost:8080/prices/currency/EUR