### create product
POST http://localhost:8080/product
Content-Type: application/json

{
  "productName": "samsung X20",
  "prices": [
    {
      "amount": 19.99,
      "currency": "EUR",
      "description": "price from 11.03.2020"
    }
  ],
  "categories": [
    8
  ]
}

### find all
GET http://localhost:8080/product

### find by id
GET http://localhost:8080/product/4

### delete by id
DELETE http://localhost:8080/product/4

### find by name
GET http://localhost:8080/product/productName
Content-Type: application/json

{
  "productName": "samsung_xt25"
}

### find by price.amount
GET http://localhost:8080/product/productPrice/25

### find by category id
GET http://localhost:8080/product/productCategory/1

### find all product by currency
GET http://localhost:8080/product/currency/USD

### find products with price between price start and price end.
GET http://localhost:8080/product/productBetween/25/29